# docker-compose.yml
version: '3.8'
services:
  now-upload:
    image: "now-upload:v1"
    restart: unless-stopped
    volumes:
      - ./volumes/resources:/app/server/html/resources
    ports:
      - 3000:3000
# networks:
#   default:
#     external:
#       name: main